### ISSUE TITLE
Mobile Browsers?

### ISSUE THREAD

**Issue by Cyber5imon** [goobemaster/kodenkel-fo-hacking#1]
Doesn't seem to work on mobile browsers.
Tested with Chrome 96, Android 10.

**Comment by goobemaster** [comment]
Thanks for letting me know. I'll think about a solution.

When I had a brief look it looked somewhat supported, but highlighting by clicking seems to be off on mobile indeed.

**Comment by goobemaster** [comment]
Hey @SPDurkee , could you have a look and let me know what you think?

Note: I had to open the page in incognito mode on Android Chrome, otherwise the old JS was loaded from cache.
https://www.kodenkel.com/games/fo-hacking/

**Comment by goobemaster** [comment]
I consider this done. Feel free to add a comment, or open a new issue if you find something.
